import type { Rule } from "./types";

/**
 * 初期ルール（たたき台）。
 * 【要確認】算定要件は令和8年度改定の告示・通知・疑義解釈で必ず確認してから有効にすること。
 * 本番の優先順位は、実際の返戻・査定実績（ルール画面の実績CSV）で並べ替える。
 * 名称はマスター名称の部分一致（全角半角・空白は無視）で当てる。
 */
const CHECK = "令和8年度改定の告示・通知で要件を確認してください。";

export const BUILTIN_RULES: Rule[] = [
  {
    id: "prereq-srp-perio-exam",
    kind: "prerequisite",
    name: "SRPの前に歯周病検査",
    category: "prerequisite",
    impact: "satei",
    enabled: true,
    priority: 1,
    source: "builtin",
    target: { names: ["スケーリング・ルート・プレーニング", "SRP"] },
    required: { names: ["歯周基本検査", "歯周精密検査", "混合歯列期歯周病検査"] },
    lookbackMonths: 6,
    mustPrecede: true,
    basis: "歯周病の治療は歯周病検査の結果に基づいて行うこととされている。",
    fix: "検査を実施していれば検査の算定を追加。未実施ならSRPを算定しない。",
    note: CHECK,
  },
  {
    id: "diag-srp-perio",
    kind: "diagnosis",
    name: "SRPに歯周炎の病名",
    category: "diagnosis",
    impact: "satei",
    enabled: true,
    priority: 2,
    source: "builtin",
    target: { names: ["スケーリング・ルート・プレーニング", "SRP"] },
    diagnosis: { names: ["歯周炎"] },
    matchTooth: true,
    basis: "処置は、その部位の傷病名に対して行うものである。",
    fix: "該当部位に歯周炎の病名を付けるか、部位の記載を確認。",
    note: CHECK,
  },
  {
    id: "diag-pulpectomy-pulpitis",
    kind: "diagnosis",
    name: "抜髄に歯髄炎の病名",
    category: "diagnosis",
    impact: "satei",
    enabled: true,
    priority: 3,
    source: "builtin",
    target: { names: ["抜髄"] },
    diagnosis: { names: ["歯髄炎"] },
    matchTooth: true,
    basis: "処置は、その部位の傷病名に対して行うものである。",
    fix: "該当歯に歯髄炎の病名があるか確認し、なければ病名を追加。",
    note: CHECK,
  },
  {
    id: "diag-infected-canal",
    kind: "diagnosis",
    name: "感染根管処置に対応する病名",
    category: "diagnosis",
    impact: "satei",
    enabled: true,
    priority: 4,
    source: "builtin",
    target: { names: ["感染根管処置"] },
    diagnosis: { names: ["根尖性歯周炎", "歯髄壊死", "歯髄壊疽"] },
    matchTooth: true,
    basis: "処置は、その部位の傷病名に対して行うものである。",
    fix: "該当歯の病名（根尖性歯周炎など）を確認。",
    note: CHECK,
  },
  {
    id: "freq-shikan-month",
    kind: "frequency",
    name: "歯科疾患管理料は月1回",
    category: "frequency",
    impact: "satei",
    enabled: true,
    priority: 5,
    source: "builtin",
    target: { names: ["歯科疾患管理料"], excludeNames: ["加算"] },
    max: 1,
    per: "month",
    basis: "歯科疾患管理料は月1回に限り算定するとされている。",
    fix: "同月2回目以降の算定を削除。",
    note: CHECK,
  },
  {
    id: "freq-jicchi-month",
    kind: "frequency",
    name: "歯科衛生実地指導料は月1回",
    category: "frequency",
    impact: "satei",
    enabled: true,
    priority: 6,
    source: "builtin",
    target: { names: ["歯科衛生実地指導料"], excludeNames: ["加算"] },
    max: 1,
    per: "month",
    basis: "歯科衛生実地指導料は月1回に限り算定するとされている。",
    fix: "同月2回目以降の算定を削除。",
    note: CHECK,
  },
  {
    id: "freq-pmtc-2months",
    kind: "frequency",
    name: "機械的歯面清掃処置は2月に1回",
    category: "frequency",
    impact: "satei",
    enabled: true,
    priority: 7,
    source: "builtin",
    target: { names: ["機械的歯面清掃処置"] },
    max: 1,
    per: "months",
    months: 2,
    basis: "機械的歯面清掃処置は原則2月に1回に限り算定するとされている（患者の状態等により月1回算定できる場合あり）。",
    fix: "前月にも算定していないか確認。月1回算定できる条件に当たる場合は該当コメント等を確認。",
    note: CHECK,
  },
  {
    id: "excl-shoshin-saishin",
    kind: "exclusive",
    name: "同日の初診料と再診料",
    category: "exclusive",
    impact: "satei",
    enabled: true,
    priority: 8,
    source: "builtin",
    a: { names: ["初診料"], excludeNames: ["加算"] },
    b: { names: ["再診料"], excludeNames: ["加算"] },
    scope: "day",
    basis: "同一日に初診料と再診料は併せて算定できない。",
    fix: "どちらか一方にする（通常は再診料を削除）。",
    note: CHECK,
  },
  {
    id: "excl-perio-basic-precise",
    kind: "exclusive",
    name: "同月の歯周基本検査と歯周精密検査",
    category: "exclusive",
    impact: "satei",
    enabled: true,
    priority: 9,
    source: "builtin",
    a: { names: ["歯周精密検査"] },
    b: { names: ["歯周基本検査"] },
    scope: "month",
    basis: "歯周病検査は同月に種類の異なる検査を併せて算定できないとされている。",
    fix: "同月に両方算定していれば一方を削除。",
    note: CHECK,
  },
  {
    id: "comment-houmon-time",
    kind: "comment",
    name: "歯科訪問診療料の実施時刻コメント",
    category: "comment",
    impact: "henrei",
    enabled: true,
    priority: 10,
    source: "builtin",
    target: { names: ["歯科訪問診療"], excludeNames: ["加算"] },
    comment: { keywords: ["時"] },
    basis: "歯科訪問診療料は、実施時刻等をレセプトに記載することとされている。",
    fix: "実施時刻（開始・終了）のコメントを追加。",
    note: CHECK,
  },
  {
    id: "facility-cadcam-required",
    kind: "facility",
    name: "CAD/CAM冠は届出が必要",
    category: "facility",
    impact: "satei",
    enabled: true,
    priority: 11,
    source: "builtin",
    standard: "CAD/CAM冠及びCAD/CAMインレー",
    mode: "required",
    target: { names: ["CAD/CAM冠", "CAD/CAMインレー"] },
    basis: "CAD/CAM冠は施設基準に適合し届出た医療機関で算定できる。",
    fix: "届出済みなら設定画面の施設基準を更新。未届なら算定できない。",
    note: CHECK,
  },
  {
    id: "facility-anzen-missed",
    kind: "facility",
    name: "外来安全対策加算の算定漏れ（初診）",
    category: "facility",
    impact: "more",
    enabled: true,
    priority: 12,
    source: "builtin",
    standard: "歯科外来診療医療安全対策加算1",
    mode: "missed",
    when: { names: ["初診料"], excludeNames: ["加算"] },
    expect: { names: ["医療安全対策加算"] },
    basis: "施設基準を届け出た医療機関は、初診時に加算を算定できる。",
    fix: "初診料に加算を追加。",
    note: CHECK,
  },
  {
    id: "facility-kansen-missed",
    kind: "facility",
    name: "外来感染対策加算の算定漏れ（初診）",
    category: "facility",
    impact: "more",
    enabled: true,
    priority: 13,
    source: "builtin",
    standard: "歯科外来診療感染対策加算1",
    mode: "missed",
    when: { names: ["初診料"], excludeNames: ["加算"] },
    expect: { names: ["感染対策加算"] },
    basis: "施設基準を届け出た医療機関は、初診時に加算を算定できる。",
    fix: "初診料に加算を追加。",
    note: CHECK,
  },
];
