import type { OfficialRule, Rule } from "./types";

/**
 * 初期ルール。
 *
 * 1. 公式テーブル（支払基金の基本マスター令和8年版に収載）
 *    算定回数限度・併算定背反・年齢制限・コメント関連・施設基準は、マスターから自動で点検する。
 * 2. 手書きルール（公式テーブルに無い、審査でよく見られる観点）
 *    コードは歯科診療行為マスター（令和8年版）のもの。名称はマスター名称の部分一致（全角半角は無視）。
 *
 * 【要確認】手書きルールの算定要件は、告示・通知・疑義解釈で確認してから本番で有効にすること。
 * 本番の優先順位は、各医院の返戻・査定実績（ルール画面の実績CSV）で並べ替える。
 */

const OFFICIAL_NOTE = "支払基金「基本マスター」（令和8年版）のテーブルから自動で点検します。";

export const OFFICIAL_RULES: OfficialRule[] = [
  {
    id: "official-limit",
    kind: "official",
    table: "limit",
    name: "算定回数の上限（公式：算定回数限度テーブル）",
    category: "frequency",
    impact: "satei",
    enabled: true,
    priority: 1,
    source: "official",
    basis: "歯科診療行為マスター「算定回数限度テーブル」に定められた算定単位ごとの上限回数。",
    fix: "上限を超えた分の算定を削除するか、算定日・回数の入力誤りを確認。",
    note: OFFICIAL_NOTE,
  },
  {
    id: "official-exclusive",
    kind: "official",
    table: "exclusive",
    name: "併算定できない組み合わせ（公式：併算定背反テーブル）",
    category: "exclusive",
    impact: "satei",
    enabled: true,
    priority: 2,
    source: "official",
    basis: "歯科診療行為マスター「併算定背反テーブル」に定められた、同一月に併せて算定できない組み合わせ。",
    fix: "どちらか一方の算定にする。",
    note: `${OFFICIAL_NOTE} 歯科のテーブルには範囲（同日・同月）の項目が無いため、同一月として点検します。`,
  },
  {
    id: "official-comment",
    kind: "official",
    table: "comment",
    name: "必須コメントの記録漏れ（公式：コメント関連テーブル）",
    category: "comment",
    impact: "henrei",
    enabled: true,
    priority: 3,
    source: "official",
    basis: "「診療報酬請求書等の記載要領」別表Ⅰ（歯科）で、算定した場合に記録が必要とされるコメント。",
    fix: "記載要領に沿ってコメント（コメントコード）を追加。",
    note: `${OFFICIAL_NOTE} 算定しただけで記録が必要になるもの（条件区分01）に限り、各項目で最低1つのコメントがあるかを確認します。`,
  },
  {
    id: "official-facility",
    kind: "official",
    table: "facility",
    name: "施設基準の届出が必要な項目（公式：基本テーブルの施設基準）",
    category: "facility",
    impact: "satei",
    enabled: true,
    priority: 4,
    source: "official",
    basis: "歯科診療行為マスター基本テーブルの「施設基準」欄に設定された施設基準の届出が必要。",
    fix: "届出済みなら設定画面の施設基準を更新。未届出なら届出不要の項目（「未届出」の点数など）で算定する。",
    note: `${OFFICIAL_NOTE} 医院の施設基準（設定画面）が1つも登録されていないときは点検しません。`,
  },
  {
    id: "official-age",
    kind: "official",
    table: "age",
    name: "年齢の条件（公式：年齢制限テーブル）",
    category: "prerequisite",
    impact: "satei",
    enabled: true,
    priority: 5,
    source: "official",
    basis: "歯科診療行為マスター「年齢制限テーブル」に定められた算定可能な年齢。",
    fix: "患者の年齢に合った項目で算定する（生年月日の入力誤りも確認）。",
    note: `${OFFICIAL_NOTE} 月内のどの日でも条件を満たさない場合だけ指摘します。`,
  },
];

const CHECK = "令和8年度改定の告示・通知・疑義解釈で要件を確認してください。";

const SRP = { names: ["スケーリング・ルートプレーニング"] };

export const CUSTOM_RULES: Rule[] = [
  {
    id: "prereq-srp-perio-exam",
    kind: "prerequisite",
    name: "SRPの前に歯周病検査",
    category: "prerequisite",
    impact: "satei",
    enabled: true,
    priority: 6,
    source: "builtin",
    target: SRP,
    required: { names: ["歯周基本検査", "歯周精密検査", "混合歯列期歯周病検査"] },
    lookbackMonths: 6,
    mustPrecede: true,
    basis: "歯周病の治療は歯周病検査の結果に基づいて行うこととされている。",
    fix: "検査を実施していれば検査の算定を追加。未実施ならSRPを算定しない。",
    note: CHECK,
  },
  {
    id: "diag-srp-perio",
    kind: "diagnosis",
    name: "SRPに歯周炎（P）の病名",
    category: "diagnosis",
    impact: "satei",
    enabled: true,
    priority: 7,
    source: "builtin",
    target: SRP,
    diagnosis: { names: ["歯周炎"], abbrs: ["P", "P急発"] },
    matchTooth: true,
    perTooth: true,
    basis: "処置は傷病名に対して行うもので、SRPは1歯単位で算定する。",
    fix: "歯周炎の病名と部位（歯式）を確認し、不足していれば追加。",
    note: CHECK,
  },
  {
    id: "diag-pulpectomy-pulpitis",
    kind: "diagnosis",
    name: "抜髄に歯髄炎（Pul）の病名",
    category: "diagnosis",
    impact: "satei",
    enabled: true,
    priority: 8,
    source: "builtin",
    target: { names: ["抜髄"] },
    diagnosis: { names: ["歯髄炎"], abbrs: ["Pul"] },
    matchTooth: true,
    perTooth: true,
    basis: "処置は傷病名に対して行うもので、抜髄は1歯単位で算定する。",
    fix: "該当歯の歯髄炎の病名と部位を確認し、不足していれば追加。",
    note: CHECK,
  },
  {
    id: "diag-infected-canal",
    kind: "diagnosis",
    name: "感染根管処置に対応する病名",
    category: "diagnosis",
    impact: "satei",
    enabled: true,
    priority: 9,
    source: "builtin",
    target: { names: ["感染根管処置"] },
    diagnosis: { names: ["根尖性歯周炎", "歯髄壊死", "歯髄壊疽"], abbrs: ["Per", "Puエシ", "Puエソ"] },
    matchTooth: true,
    perTooth: true,
    basis: "処置は傷病名に対して行うもので、感染根管処置は1歯単位で算定する。",
    fix: "該当歯の病名（根尖性歯周炎など）と部位を確認。",
    note: CHECK,
  },
  {
    id: "excl-shoshin-saishin",
    kind: "exclusive",
    name: "同日の初診料と再診料",
    category: "exclusive",
    impact: "satei",
    enabled: true,
    priority: 10,
    source: "builtin",
    a: { names: ["歯科初診料", "地域歯科診療支援病院歯科初診料"] },
    b: { names: ["歯科再診料"] },
    scope: "day",
    basis: "同一日に初診料と再診料は併せて算定できない。",
    fix: "どちらか一方にする（通常は再診料を削除）。",
    note: CHECK,
  },
  {
    id: "excl-perio-basic-precise",
    kind: "exclusive",
    name: "同月の歯周基本検査と歯周精密検査",
    category: "exclusive",
    impact: "satei",
    enabled: true,
    priority: 11,
    source: "builtin",
    a: { names: ["歯周精密検査"] },
    b: { names: ["歯周基本検査"] },
    scope: "month",
    basis: "歯周病検査は同一月に種類の異なる検査を併せて算定できないとされている。",
    fix: "同月に両方算定していれば一方を削除。",
    note: CHECK,
  },
  {
    id: "facility-anzen-missed",
    kind: "facility",
    name: "外来安全対策加算の算定漏れ（初診）",
    category: "facility",
    impact: "more",
    enabled: true,
    priority: 12,
    source: "builtin",
    standard: "1352",
    mode: "missed",
    when: { codes: ["301000110"] },
    expect: { codes: ["301001570"] },
    expectPoints: 12,
    basis: "歯科外来診療医療安全対策加算１の施設基準を届け出た医療機関は、初診時に加算できる。",
    fix: "初診料に加算を追加。",
    note: CHECK,
  },
  {
    id: "facility-kansen-missed",
    kind: "facility",
    name: "外来感染対策加算の算定漏れ（初診）",
    category: "facility",
    impact: "more",
    enabled: true,
    priority: 13,
    source: "builtin",
    standard: "1370",
    mode: "missed",
    when: { codes: ["301000110"] },
    expect: { codes: ["301123070"] },
    expectPoints: 12,
    basis: "歯科外来診療感染対策加算１の施設基準を届け出た医療機関は、初診時に加算できる。",
    fix: "初診料に加算を追加。",
    note: CHECK,
  },
];

export const BUILTIN_RULES: Rule[] = [...OFFICIAL_RULES, ...CUSTOM_RULES];
